GET http://localhost:3000/user/get

###
POST http://localhost:3000/user/create
Content-Type: application/json

{
    "userName" : "esuraj",
    "name" : "Suraj Pandey",
    "userEmail" : "esuraj@gmail.com",
    "userPhone" : "7631485296",
    "userPassword" : "123456",
    "userLanguage" : "Hindi",
    "userDob" : "2022-01-12",
    "userProfile" : "http://122d/userprofile"
}

###
POST http://localhost:3000/user/create
Content-Type: application/json

{
    "userName" : "esurya",
    "name" : "Surya Pandey",
    "userEmail" : "esurya@gmail.com",
    "userPhone" : "7631985296",
    "userPassword" : "123456",
    "userLanguage" : "Hindi",
    "userDob" : "2022-01-12",
    "userProfile" : "122dfjhkjfddfshkhedg"
}
###
POST http://localhost:3000/user/create
Content-Type: application/json

{
    "userName" : "sanju",
    "name" : "Sanju Pandey",
    "userEmail" : "esanju@gmail.com",
    "userPhone" : "7631795296",
    "userPassword" : "123456",
    "userLanguage" : "Hindi",
    "userDob" : "2022-01-12",
    "userProfile" : "122dfjhkjfddfshkhedg"
}
###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "userEmail" : "esurya@gmail.com",
    "userPassword" : "123456"
}

###
POST http://localhost:3000/user/create
Content-Type: application/json

{
    "userName" : "Ranju",
    "name" : "Ranju Devi",
    "userEmail" : "eranju@gmail.com",
    "userPhone" : "7485963214",
    "userPassword" : "123456",
    "userLanguage" : "Tamil",
    "userDob" : "2022-01-12",
    "userProfile" : "122dfjhkjfddfshkhedg"
}

###
POST http://localhost:3000/user/search
Content-Type: application/json

{
    "headers" :"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjUyOTE2NTAsImV4cCI6MTY3MzkzMTY1MH0.BGjnKKAZE4QYWM1LcbfM7bTAZvA54V6F-U1o-72MRdY"
}